version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /project/applications/app/node_modules
      - ./applications/app:/project/applications/app
    ports:
      - "3000:3000"
    env_file:
      - applications/app/.env
  app-couchdb:
    image: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
